workflows:
  ios-release:
    name: DrycleanPlus iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.drycleanplus.service.uk.app
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and sign
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
